services:

  Twc\BusBundle\Event\EventBusDispatcher:
    arguments: [!tagged 'twc_bus.event.handler']

  Twc\BusBundle\Command\CommandBusFactory: ~

  Twc\BusBundle\Command\CommandBus:
    factory: ['Twc\BusBundle\Command\CommandBusFactory', 'build']
    arguments:
      - !tagged 'twc_bus.command.handler'
      - !tagged 'twc_bus.command.middleware'
    lazy: true

  Twc\BusBundle\Query\QueryBusDispatcher:
    arguments: [!tagged 'twc_bus.query.handler']

  Twc\BusBundle\Event\EventBusDispatcherMiddleware:
    arguments: ['@Twc\BusBundle\Event\EventBusDispatcher']
    tags: ['twc_bus.command.middleware']